// Style
import "./globals.css";

// Fonts
import { Rubik } from "next/font/google";

// Fonts Variables
const rubik = Rubik({
  subsets: ["latin"],
  preload: true,
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <main>
          <section className="wrapper" id="wrapper">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
